### ISSUE TITLE
在kdevelop里的编译问题

### ISSUE THREAD

**Issue by Dorothy-2016** [heguixiang/Remove_ROS_VINS#1]
您好，这个直接在kdevelop里能编译成功吗？我直接下载编译出现了了跟ros相关的问题，这个是已经完整去掉ros的版本吗？（同时，感谢您的工作，很棒！）

**Comment by heguixiang** [comment]
请贴下你的报错log，目前vins-estimator ros机制去掉了，AR的没去

**Comment by Dorothy-2016** [comment]
/home/dorothy/Remove_ROS_VINS/vins_estimator/build> make -j2
Scanning dependencies of target vins_estimator
[  7%] Building CXX object CMakeFiles/vins_estimator.dir/src/feature_tracker/feature_tracker.cpp.o
[  7%] Building CXX object CMakeFiles/vins_estimator.dir/src/estimator_node.cpp.o
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/feature_tracker/feature_tracker.cpp: In member function ‘void FeatureTracker::rejectWithF()’:
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/feature_tracker/feature_tracker.cpp:188:13: warning: unused variable ‘size_a’ [-Wunused-variable]
         int size_a = prev_pts.size();
             ^
[ 11%] Linking CXX executable vins_estimator
CMakeFiles/vins_estimator.dir/src/estimator_node.cpp.o: In function `main':
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/estimator_node.cpp:967: undefined reference to `camodocal::CameraFactory::instance()'
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/estimator_node.cpp:967: undefined reference to `camodocal::CameraFactory::generateCameraFromYamlFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/vins_estimator.dir/src/loop-closure/loop_closure.cpp.o: In function `DLoopDetector::TemplatedLoopDetector<boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >, DBoW2::FBrief>::initCameraModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/loop-closure/TemplatedLoopDetector.h:618: undefined reference to `camodocal::CameraFactory::instance()'
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/loop-closure/TemplatedLoopDetector.h:618: undefined reference to `camodocal::CameraFactory::generateCameraFromYamlFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/vins_estimator.dir/src/feature_tracker/feature_tracker.cpp.o: In function `FeatureTracker::readIntrinsicParameter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/feature_tracker/feature_tracker.cpp:215: undefined reference to `camodocal::CameraFactory::instance()'
/home/dorothy/Remove_ROS_VINS/vins_estimator/src/feature_tracker/feature_tracker.cpp:215: undefined reference to `camodocal::CameraFactory::generateCameraFromYamlFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/vins_estimator.dir/build.make:792: recipe for target 'vins_estimator' failed
make[2]: *** [vins_estimator] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vins_estimator.dir/all' failed
make[1]: *** [CMakeFiles/vins_estimator.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
*** Failure: Exit code 2 ***

**Comment by Dorothy-2016** [comment]
我现在用kdevelop直接打开vins-estimator工程，最开始是报在用到camodocal的时候报里面的头文件找不到，于是我换成了绝对路径，现在报的就是上面帖出来的错误

**Comment by heguixiang** [comment]
编译步骤如下：
1. mkdir vins_ws
2.git clone git@github.com:heguixiang/Remove_ROS_VINS.git
3.catkin_make

你上面的问题首先不是ros问题，是找不到camodocal相关函数的定义，不是在src下建立build子文件夹，而是在src的同级目录下

**Comment by Dorothy-2016** [comment]
您好，我按您说的这样确实可以编译成功,生成了一个vins_estimator的可执行文件，我现在比较疑惑的是如果去掉了ROS，不就不用工作空间这种机制了吗？之前提到的关于ros的问题，也是在vins_estimator目录下的CMakeLists.txt里第9行有一句find_package(catkin REQUIRED COMPONENTS camera_model)里 catkin出错，于是我把它注释掉了，所以上面贴的错误里没有报这个错误。（第28行catkin_package()我也注释掉了）

**Comment by heguixiang** [comment]
你说的是对的，如果要去掉工作空间机制，代码需要改一下

**Comment by Dorothy-2016** [comment]
能出一个没有工作空间机制的版本吗？或者可以指导一下吗？

**Comment by heguixiang** [comment]
这两天忙完手头的事情，我来出一个

**Comment by Dorothy-2016** [comment]
好的，感谢感谢！

**Comment by Dorothy-2016** [comment]
您好，看了您的代码里输入是需要配置文件、图片、时间、imu，这里的时间好像是指图片的采集时间，可以上传一组数据我实验一下吗？

**Comment by heguixiang** [comment]
最新版本已经去除了工作空间机制，至于你上面问到的问题，请看README

**Comment by Dorothy-2016** [comment]
OK!Very thanks!
