### ISSUE TITLE
redefinition of ‘class TicToc’

### ISSUE THREAD

**Issue by wolf943134497** [heguixiang/Remove_ROS_VINS#16]
[  2%] Building CXX object CMakeFiles/vins_estimator.dir/src/estimator_node.cpp.o
In file included from /vins-mono/src/vins_estimator/src/feature_tracker/feature_tracker.h:17:0,
                 from /vins-mono/src/vins_estimator/src/estimator_node.cpp:29:
/vins-mono/src/vins_estimator/src/feature_tracker/tic_toc.h:7:7: error: redefinition of ‘class TicToc’
 class TicToc
       ^
In file included from /vins-mono/src/vins_estimator/src/estimator.h:6:0,
                 from /vins-mono/src/vins_estimator/src/estimator_node.cpp:11:
/vins-mono/src/vins_estimator/src/utility/tic_toc.h:7:7: error: previous definition of ‘class TicToc’
 class TicToc
       ^
CMakeFiles/vins_estimator.dir/build.make:62: recipe for target 'CMakeFiles/vins_estimator.dir/src/estimator_node.cpp.o' failed

**Comment by FanTuan7** [comment]
Your compliler might not support "paragma once"
find files where the class is defined， then replace
 “#pragma once” 
by 
"#ifndef TICTOC_H_
 #define TICTOC_H_
 ......
 #endif".  works for me.
