### ISSUE TITLE
Android版本编译运行

### ISSUE THREAD

**Issue by shengxingdong** [heguixiang/Remove_ROS_VINS#2]
按照去掉ROS的版本成功编译到android端，但是在高通820的平台上运行效率很差，主要是后端optimization的时间太长，需要500~1000ms左右，而前端部分的计算速度平均30ms左右，感觉比较奇怪，不知为什么。
如果使用VINS Mobile版本的实现代码会有改善吗？好像差别不大

**Comment by heguixiang** [comment]
目前我也正在着手移植VINS-Mono到android上，如果你已经做了这个工作，能否上传上来，我就不做重复的工作了，谢谢。之前有在arm-linux环境下做个性能测试，4核a17，加上闭环，平均耗时300ms左右

**Comment by shengxingdong** [comment]
我直接写的Android.mk，如下，依赖的三方库需要自己编译


LOCAL_PATH := $(call my-dir)

#---------------thirdparty static----------
include $(CLEAR_VARS)
LOCAL_MODULE := boost_system_static
LOCAL_SRC_FILES := VINS/Thirdparty/boost/boost_1_64/android/$(APP_ABI)/lib/libboost_system.a 
include $(PREBUILT_STATIC_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := boost_serialization_static
LOCAL_SRC_FILES := VINS/Thirdparty/boost/boost_1_64/android/$(APP_ABI)/lib/libboost_serialization.a 
include $(PREBUILT_STATIC_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := boost_filesystem_static
LOCAL_SRC_FILES := VINS/Thirdparty/boost/boost_1_64/android/$(APP_ABI)/lib/libboost_filesystem.a 
include $(PREBUILT_STATIC_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := boost_program_options_static
LOCAL_SRC_FILES := VINS/Thirdparty/boost/boost_1_64/android/$(APP_ABI)/lib/libboost_program_options.a 
include $(PREBUILT_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := ceres_static
LOCAL_SRC_FILES := VINS/Thirdparty/ceres-solver/jni/obj/local/$(APP_ABI)/libceres.a 
include $(PREBUILT_STATIC_LIBRARY)
#-----------------------------------------


include $(CLEAR_VARS)
#----------------opencv------------------- 
OPENCV_INSTALL_MODULES:=on
OPENCV_CAMERA_MODULES:=off
OPENCV_LIB_TYPE:=STATIC

include $(LOCAL_PATH)/../opencv_sdk/native/jni/OpenCV.mk

#----------------------------------------- 

LOCAL_MODULE := VINS_Android 


LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS
#LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/vins_estimator/src
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/camera_model/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty/eigen3
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty/boost/boost_1_64
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty/ceres-solver/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty/ceres-solver/config
LOCAL_C_INCLUDES += $(LOCAL_PATH)/VINS/Thirdparty/ceres-solver/internal/ceres/miniglog

#MY_CPP_LIST := $(wildcard $(LOCAL_PATH)/*.cpp)
MY_CPP_LIST := $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/factor/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/feature_tracker/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/initial/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/loop-closure/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/loop-closure/ThirdParty/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/loop-closure/ThirdParty/DBoW/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/loop-closure/ThirdParty/DUtils/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/loop-closure/ThirdParty/DVision/*.cpp)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/vins_estimator/src/utility/*.cpp)

MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/*.cc)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/calib/*.cc)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/camera_models/*.cc)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/chessboard/*.cc)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/gpl/*.cc)
MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/VINS/camera_model/src/sparse_graph/*.cc)

#MY_CPP_LIST += $(wildcard $(LOCAL_PATH)/utility/*.cpp)
#MY_CPP_LIST += $(LOCAL_PATH)/ImageProcess_jni.cpp

LOCAL_SRC_FILES := $(MY_CPP_LIST:$(LOCAL_PATH)/%=%)

LOCAL_STATIC_LIBRARIES += ceres_static 
LOCAL_STATIC_LIBRARIES += boost_system_static
LOCAL_STATIC_LIBRARIES += boost_serialization_static
LOCAL_STATIC_LIBRARIES += boost_filesystem_static
LOCAL_STATIC_LIBRARIES += boost_program_options_static
 
LOCAL_LDLIBS += -lm -llog -lz
include $(BUILD_SHARED_LIBRARY)

**Comment by shengxingdong** [comment]
定位下来，void MarginalizationInfo::marginalize() 里面的计算太慢了

**Comment by Dorothy-2016** [comment]
@shengxingdong 请问你是用实时android摄像头和IMU还是本地数据测试的?

**Comment by shengxingdong** [comment]
@Dorothy-2016 本地的数据测试

**Comment by heguixiang** [comment]
移植到android后（armeabi-v7a , g++ 4.9），会出现下面log，网上搜了一下说的意思好像是编译器不支持不定长数组声明，你有出现此类问题吗？@shengxingdong 
![image](https://user-images.githubusercontent.com/16131498/30688267-458c6fbe-9ef0-11e7-8366-b9f6cac42cbc.png)

**Comment by shengxingdong** [comment]
没有出现以上问题
我用的eigen3，ndk11，不知道会不会是这个关系。

**Comment by heguixiang** [comment]
@shengxingdong 调用VINS需要给4个参数，不管是将vins_estimator编程so库还是jni直接调用vins_estimator 的main函数。所以我想问的是，config配置文件和dataset放在哪，jni如何传递这个路径参数，Android 新手，求指教

**Comment by shengxingdong** [comment]
我编译的是so库，把main函数改个名字变成一个接口，然后用app去调用运行的。

如果你的android机器是root的，可以直接编译成executable的程序，直接push到android设备中用adb运行就行了，把配置文件和dataset可以放在sdcard目录下某个地方，运行的时候指定对应位置即可，和Ubuntu下一样。

**Comment by heguixiang** [comment]
就是这么做的，编译成so库，这个某个地方有要求吗，我试过根目录，/Android/data和/data目录均不行，你是放在什么位置

**Comment by shengxingdong** [comment]
我放在/sdcard/自建目录/
没有root权限，没法访问data目录吧

**Comment by heguixiang** [comment]
@shengxingdong ，你的Android手机什么配置，几核CPU，最高频有多少？SRAM多大？Ceres非线性优化需要多久时间？谢谢！我这边4核A17的，1.4GHz，1.5G SRAM， ceres需要好几秒，慢的有点不太正常了，但是最终计算出来的数据还是对的

**Comment by shengxingdong** [comment]
@heguixiang 我手机是高通820cpu，ceres solver时间大概70ms左右，可能你的迭代次数和时间限制的参数没有设置正确

**Comment by heguixiang** [comment]
给你个思路，ceres代码里有设最大迭代优化时间，我的手机如果按照默认的时间非线性优化答案也不对，必须调大这个时间才能得到正确结果，我这里的原因就是因为最大时间的限制，ceres的优化根本没有收敛



发自我的小米手机
在 sindo <notifications@github.com>，2017年10月12日 10:02写道：

@heguixiang<https://github.com/heguixiang> 我手机是高通820cpu，ceres时间倒是比较快，主要是marginlization步骤很慢，要几百毫秒，并且现在存在跑数据集结果不对的问题，还在查原因

**Comment by huangju91** [comment]
你好，我移到android端也是数据集结果不对，调大最大迭代时间，位姿画出来少了一大截啊

**Comment by jackyfriend** [comment]
@shengxingdong 可以发下你改的代码出来学习下吗？
