### ISSUE TITLE
Why my result is like this?

### ISSUE THREAD

**Issue by Dorothy-2016** [heguixiang/Remove_ROS_VINS#3]
![screenshot from 2017-09-21 12-08-22](https://user-images.githubusercontent.com/23702750/30681887-f25de5f4-9ed9-11e7-9a35-2dde58d3e82c.png)

Why my result is like this,I have run like your readme.txt, the result looks like after it read the euroc_config.yaml,it stay there without the output of position.
Sorry about the english description for my computer now cannot input in chinese(>_<)

**Comment by heguixiang** [comment]
Please debug it by yourself， the log you paste seems OK. and following picture is my output log. But I can give you two clues to debug: 1. Is the parameter set correctly?（vins_estimator/src/parameters.cpp）2. Is the system have input data?(vins_estimator/src/estimator_node.cpp LoadImages and LoadImu function)
![image](https://user-images.githubusercontent.com/16131498/30682665-09dfa08e-9edd-11e7-988d-56cfcecea275.png)

**Comment by Dorothy-2016** [comment]
Ok! Thanks!

**Comment by xiaomage11** [comment]
@Dorothy-2016  I see you run passed, but I face to some question, could you help me .when i run the ./generate.sh ,it show issues:/usr/include/eigen3/Eigen/src/SparseCore/SparseDenseProduct.h:51:71: error: expected unqualified-id before end of line . I want to know how to install the eigen3.2.0, I install the eigen3.2.0 follow the internet.
