### ISSUE TITLE
显示

### ISSUE THREAD

**Issue by jixiedaima** [heguixiang/Remove_ROS_VINS#5]
做了简单的测试，没有可视化界面吗？程序跑到一半显示段错误？
不知道是不是我的配置问题

**Comment by heguixiang** [comment]
已添加UI，你的段错误不清楚什么问题，我这边没有这个问题，其他人好像也没有反映这个问题

**Comment by huangju91** [comment]
@jixiedaima 我也是没界面且段错误，请问你咋解决的？

**Comment by heguixiang** [comment]
Make sure you have installed pangolin, the software detail dependency can find on README

发件人: huangju91 [mailto:notifications@github.com]
发送时间: 2018年1月10日 10:13
收件人: heguixiang/Remove_ROS_VINS
抄送: Solomon He; State change
主题: Re: [heguixiang/Remove_ROS_VINS] 显示 (#5)


@jixiedaima<https://github.com/jixiedaima> 我也是没界面且段错误，请问你咋解决的？
