### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by shengxingdong** [heguixiang/Remove_ROS_VINS#6]
I got a running error at the beginning of program:

X11 Error: BadValue (integer parameter out of range for operation)
X11 Error: BadValue (integer parameter out of range for operation)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Failed to create an OpenGL context

**Comment by heguixiang** [comment]
Make sure you have installed Pangolin which was used for UI.

**Comment by xiaomage11** [comment]
@shengxingdong Do you run pass ? I face to some question could you help me .when i run the ./generate.sh it show issues:/usr/include/eigen3/Eigen/src/SparseCore/SparseDenseProduct.h:51:71: error: expected unqualified-id before end of line . I want to know how to install the eigen3.2.0, I install the eigen3.2.0 follow the internet.
